// Copies the repository's AGENTS.md into the app as the default rules.
// Run with `pnpm rules:sync` whenever AGENTS.md changes.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const source = path.resolve(process.cwd(), "../AGENTS.md");
const target = path.resolve(process.cwd(), "src/lib/rules/default-rules.ts");
const text = readFileSync(source, "utf8");
const escaped = text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
writeFileSync(
  target,
  `// Generated by scripts/sync-rules.ts from ../AGENTS.md. Do not edit by hand.\nexport const defaultRules = \`${escaped}\`;\n`,
);
console.log(`Wrote ${target} (${text.length} characters)`);
